LL-1544: Updated e2e script
fetchoracle/telliot-feeds pull request #63
Opened 2023-11-01 16:53 UTC by jemliquidloans

Update E2E test script to work on the assumption that it will run on a newly deployed contract with no reports yet.

2023-11-02 03:36 UTC, dsm-ll requested changes

2023-11-02 03:36 UTC, dsm-ll commented on e2e_tests.py
> -    report_hash = submit_report_with_telliot(account_name=account_name, stake_amount=stake_amount)
Moving the report to a line that is previous than mock price api initialization would cause problem in the test. The logic of this specific test is to check if a price submitted is ingested by the oracle and then provided by the get_current_value function. To check that, it is necessary to make a variation in the price, since without that you don't know if the price retrieved is the one ingested or just the previous one. Mock price api  provide a variation in the price to be able to check that. With this PR we will not have this variation and thus cannot have sure that the application is working. Please revert this change.

One hint to check why this line is not working would be to check if mock price api is running an responding when we get to this line in the github actions env.

2023-11-02 03:36 UTC, dsm-ll commented on e2e_tests.py
> +
This code is suspicious to hinder a bug or problem in the github actions configuration. I think this code would not be placed here (see the next comment in the PR) and the try/catch usage without a proper error handler is inappropriate.

2023-11-03 12:34 UTC, jensendarren commented
@dsm-ll given the feedback from Jem it turns out the test script is written in such as way as to assume there is already a price submitted to the oracle. Therefore, I'll merge this temporary fix now.

2023-11-03 12:35 UTC, merged